@extends('layouts.default')


@section('main-page')


    <!-- ===== BANNER SLIDER ===== -->
    <section class="slider-section">

        @foreach($banners as $index => $banner)
            @php
                $is_video = Str::endsWith($banner->banner_image, ['.mp4', '.webm', '.ogg']);
            @endphp

            <div class="slide slide-{{ $index + 1 }} {{ $index === 0 ? 'active' : '' }}" @if(!$is_video)
            style="background-image: url('{{ env('MAIN_URL', '/') . $banner->banner_image }}');" @endif>


                @if($is_video)
                    <video autoplay muted loop playsinline class="banner-video">
                        <source src="{{ env('MAIN_URL', '/') . $banner->banner_image }}" type="video/mp4">
                    </video>
                @endif

                <div class="slide-content">
                    <a href="{{ url('estimate') }}" class="slide-btn"><span>Shop Now ✦</span></a>
                </div>
            </div>
        @endforeach

        <!-- Dots -->
        <div class="slider-dots">
            @foreach($banners as $index => $banner)
                <div class="dot {{ $index === 0 ? 'active' : '' }}" onclick="goToSlide({{ $index }})"></div>
            @endforeach
        </div>

    </section>


    <!-- ===== HERO / ABOUT SECTION ===== -->
    <section class="hero-section">
        <div class="hero-inner">

            <!-- LEFT IMAGE -->
            <div class="hero-image-wrap">
                <!-- Corner sparks -->
                <svg class="corner-spark tl" viewBox="0 0 40 40" fill="none">
                    <line x1="2" y1="2" x2="14" y2="14" stroke="#ff6a00" stroke-width="2" />
                    <line x1="2" y1="2" x2="2" y2="12" stroke="#ffd700" stroke-width="1.5" />
                    <line x1="2" y1="2" x2="12" y2="2" stroke="#ffd700" stroke-width="1.5" />
                    <circle cx="2" cy="2" r="3" fill="#ff6a00" />
                </svg>
                <svg class="corner-spark tr" viewBox="0 0 40 40" fill="none">
                    <line x1="2" y1="2" x2="14" y2="14" stroke="#ff6a00" stroke-width="2" />
                    <line x1="2" y1="2" x2="2" y2="12" stroke="#ffd700" stroke-width="1.5" />
                    <line x1="2" y1="2" x2="12" y2="2" stroke="#ffd700" stroke-width="1.5" />
                    <circle cx="2" cy="2" r="3" fill="#ff6a00" />
                </svg>
                <svg class="corner-spark bl" viewBox="0 0 40 40" fill="none">
                    <line x1="2" y1="2" x2="14" y2="14" stroke="#ff6a00" stroke-width="2" />
                    <line x1="2" y1="2" x2="2" y2="12" stroke="#ffd700" stroke-width="1.5" />
                    <line x1="2" y1="2" x2="12" y2="2" stroke="#ffd700" stroke-width="1.5" />
                    <circle cx="2" cy="2" r="3" fill="#ff6a00" />
                </svg>
                <svg class="corner-spark br" viewBox="0 0 40 40" fill="none">
                    <line x1="2" y1="2" x2="14" y2="14" stroke="#ff6a00" stroke-width="2" />
                    <line x1="2" y1="2" x2="2" y2="12" stroke="#ffd700" stroke-width="1.5" />
                    <line x1="2" y1="2" x2="12" y2="2" stroke="#ffd700" stroke-width="1.5" />
                    <circle cx="2" cy="2" r="3" fill="#ff6a00" />
                </svg>

                <img src="{{ env('MAIN_URL', '/') . $settings->welcome_image }}" alt="Bluvel Crackers" />
            </div>

            <!-- RIGHT CONTENT -->
            <div class="hero-content">
                <div class="hero-eyebrow">{{ $settings->hero_eyebrow }}</div>

                <h1 class="hero-title">{!! $settings->welcome_heading !!}</h1>
                <span class="title-underline"></span>

                <p class="hero-body">
                    {!! $settings->welcome_text !!}
                </p>

                <div class="hero-badges">
                    <div class="badge"><span class="badge-icon">🏆</span> {{ $settings->badge1_text }}</div>
                    <div class="badge"><span class="badge-icon">🔥</span> {{ $settings->badge2_text }}</div>
                    <div class="badge"><span class="badge-icon">🚀</span> {{ $settings->badge3_text }}</div>
                </div>

                <a href="{{ $settings->welcome_button_link }}" class="hero-cta"><span>✦
                        {{ $settings->welcome_button_text }}</span></a>
            </div>

        </div>
    </section>







    <!-- ===== PRODUCTS SECTION ===== -->
    <section class="products-section" id="products">

        <!-- Floating embers (generated by JS) -->
        <div id="emberContainer"></div>

        <div class="products-inner">

            <!-- Section Header -->
            <div class="section-header">
                <div class="section-eyebrow">{{ $settings->products_eyebrow ?? 'Handpicked Selection' }}</div>
                <h2 class="section-title-main">{{ $settings->products_heading ?? 'Our Products' }}</h2>
                <span class="section-title-bar"></span>
                <!-- Products Grid -->
                <div class="products-grid">

                    @foreach($products as $index => $product)
                        @if($index === 0)
                            <!-- Featured Card (wide) -->
                            <div class="product-card-fire featured">
                                <div class="product-img-wrap">
                                    <div class="product-img-circle">
                                        <img src="{{ env('MAIN_URL', '/') . $product->product_image }}"
                                            alt="{{ $product->product_name }}">
                                    </div>
                                </div>
                                <div class="featured-content">
                                    <div class="product-name">{{ $product->product_name }}</div>
                                    <div class="product-desc">
                                        {{ $product->product_desc ?? 'Premium quality for every celebration.' }}
                                    </div>
                                    <div class="product-divider"></div>
                                    <span class="product-tag">✦ {{ $product->category->category_name ?? 'Featured' }}</span>
                                </div>
                            </div>
                        @else
                            <!-- Standard Cards -->
                            <div class="product-card-fire">
                                <span class="product-number">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span>
                                <div class="product-img-wrap">
                                    <div class="product-img-circle">
                                        <img src="{{ env('MAIN_URL', '/') . $product->product_image }}"
                                            alt="{{ $product->product_name }}">
                                    </div>
                                </div>
                                <div class="product-name">{{ $product->product_name }}</div>
                                <div class="product-desc">{{ $product->product_desc ?? 'Grandeur for every festive occasion' }}
                                </div>
                                <div class="product-divider"></div>
                                <span class="product-tag">{{ $product->category->category_name ?? 'Sivakasi' }}</span>
                            </div>
                        @endif
                    @endforeach

                </div>
            </div>
    </section>





    <!-- ===== WHY CHOOSE US ===== -->
    <section class="why-section" id="why-choose-us">
        <div class="why-inner">

            <!-- Header -->
            <div class="why-header">
                <div class="why-eyebrow">{{ $settings->why_heading_data['eyebrow'] ?? 'Our Promise' }}</div>
                <h2 class="why-title">{{ $settings->why_heading_data['title'] ?? 'Why Choose Us' }}</h2>
                <span class="why-title-bar"></span>
                <p class="why-subtitle">
                    {{ $settings->why_heading_data['subtitle'] ?? "Built on quality, safety and unbeatable value — here's what sets Bluvel apart" }}
                </p>
            </div>

            <!-- Split layout -->
            <div class="why-layout">

                <!-- LEFT — Pillar list with vertical fire line -->
                <div class="why-pillar">
                    <div class="pillar-line"></div>
                    @php
                        $defaultPillars = [
                            ['icon' => 'fa-solid fa-award', 'title' => 'Best Quality', 'desc' => 'Every cracker is sourced directly from certified Sivakasi manufacturers — premium quality for every celebration.'],
                            ['icon' => 'fa-solid fa-layer-group', 'title' => 'Wide Variety', 'desc' => 'From sparklers to aerial shells — our catalogue caters to every taste, occasion and budget across India.'],
                            ['icon' => 'fa-solid fa-shield-halved', 'title' => 'Safety First', 'desc' => 'All products meet government safety standards. Your family\'s well-being is our first priority with every order.'],
                            ['icon' => 'fa-solid fa-handshake', 'title' => 'Trusted Brand', 'desc' => 'Thousands of happy customers trust Bluvel Crackers year after year for Diwali and every festival.']
                        ];
                        $savedPillars = $settings->why_pillars ?? $defaultPillars;
                    @endphp
                    @foreach($savedPillars as $index => $pillar)
                        <div class="pillar-item">
                            <div class="pillar-hex"><i class="{{ $defaultPillars[$index]['icon'] ?? 'fa-solid fa-check' }}"></i>
                            </div>
                            <div class="pillar-text">
                                <div class="pillar-name">{{ $pillar['title'] ?? '' }}</div>
                                <p class="pillar-desc">{{ $pillar['desc'] ?? '' }}</p>
                            </div>
                        </div>
                    @endforeach
                </div>

                <!-- RIGHT — Animated progress bar cards -->
                <div class="why-dial-wrap">
                    @php
                        $defaultDials = [
                            ['icon' => 'fa-solid fa-hand-holding-dollar', 'name' => 'Affordable Price', 'pct' => '97'],
                            ['icon' => 'fa-solid fa-truck-fast', 'name' => 'Quick Delivery', 'pct' => '95'],
                            ['icon' => 'fa-solid fa-clipboard-list', 'name' => 'Easy Ordering', 'pct' => '99'],
                            ['icon' => 'fa-solid fa-headset', 'name' => 'Customer Support', 'pct' => '98']
                        ];
                        $savedDials = $settings->why_dials ?? $defaultDials;
                    @endphp
                    @foreach($savedDials as $index => $dial)
                        <div class="dial-card">
                            <div class="dial-top">
                                <div class="dial-label-wrap">
                                    <div class="dial-icon"><i
                                            class="{{ $defaultDials[$index]['icon'] ?? 'fa-solid fa-star' }}"></i></div>
                                    <span class="dial-name">{{ $dial['name'] ?? '' }}</span>
                                </div>
                                <span class="dial-pct">{{ $dial['pct'] ?? '' }}%</span>
                            </div>
                            <div class="dial-track">
                                <div class="dial-fill" data-width="{{ $dial['pct'] ?? '' }}"></div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>

            <!-- Stats row -->
            <div class="why-stats">
                @php
                    $defaultStats = [
                        ['icon' => '🏆', 'number' => '5000+', 'label' => 'Happy Customers'],
                        ['icon' => '🎆', 'number' => '200+', 'label' => 'Products'],
                        ['icon' => '🔥', 'number' => '80%', 'label' => 'Max Discount'],
                        ['icon' => '🚀', 'number' => 'Pan India', 'label' => 'Delivery']
                    ];
                    $savedStats = $settings->why_stats ?? $defaultStats;
                @endphp
                @foreach($savedStats as $index => $stat)
                    <div class="stat-cell">
                        <span class="stat-icon">{{ $defaultStats[$index]['icon'] ?? '⚡' }}</span>
                        <span class="stat-number">{{ $stat['number'] ?? '' }}</span>
                        <span class="stat-label">{{ $stat['label'] ?? '' }}</span>
                    </div>
                @endforeach
            </div>

        </div>
    </section>


    <!-- ===== BRANDS / PARTNERS SECTION ===== -->
    <section class="brands-section" id="brands">

        <!-- <div class="brands-fire-border"></div> -->

        <div class="brands-inner">
            <div class="why-header">
                <div class="why-eyebrow">Certified &amp; Trusted</div>
                <h2 class="why-title">Our Brand Partners</h2>
                <span class="why-title-bar"></span>
                <!-- <p class="why-subtitle">Directly partnered with the finest Sivakasi manufacturers — bringing you authentic, licensed crackers every season.</p> -->
            </div>


            <!-- Marquee Track -->
            <div class="brands-marquee-wrap">
                @php $brandsFull = $brands->concat($brands); @endphp
                <div class="brands-marquee-track" id="brandsTrack">
                    @foreach($brandsFull as $brand)
                        <div class="brand-card-fire">
                            <div class="brand-glow-ring"></div>
                            <img src="{{ env('MAIN_URL', '/') . $brand->logo }}" alt="Brand">
                        </div>
                    @endforeach
                </div>
            </div>



        </div>

        <!-- <div class="brands-fire-border bottom"></div> -->
    </section>




    <script>
        (function () {
            const track = document.getElementById('brandsTrack');
            if (!track) return;
            track.addEventListener('touchstart', function () {
                track.style.animationPlayState = 'paused';
            }, { passive: true });
            track.addEventListener('touchend', function () {
                track.style.animationPlayState = 'running';
            }, { passive: true });
        })();
    </script>
    <script>
        (function () {
            const fills = document.querySelectorAll('.dial-fill');
            function animateBars() {
                fills.forEach(function (fill) {
                    const rect = fill.closest('.dial-card').getBoundingClientRect();
                    if (rect.top < window.innerHeight - 60 && !fill.dataset.animated) {
                        fill.dataset.animated = '1';
                        setTimeout(function () { fill.style.width = fill.dataset.width + '%'; }, 200);
                    }
                });
            }
            window.addEventListener('scroll', animateBars, { passive: true });
            animateBars();
        })();
    </script>

    <!-- ===== EMBER JS ===== -->
    <script>
        (function () {
            const container = document.getElementById('emberContainer');
            const section = container.closest('.products-section');

            function spawnEmber() {
                const el = document.createElement('div');
                el.className = 'ember-particle';

                const x = Math.random() * 100;
                const duration = 3 + Math.random() * 4;
                const delay = Math.random() * 5;
                const size = 2 + Math.random() * 3;
                const colors = ['#ff6a00', '#ffd700', '#ff4500', '#ffcc00'];
                const color = colors[Math.floor(Math.random() * colors.length)];

                el.style.cssText = `
                    left:${x}%;
                    bottom:${Math.random() * 30}%;
                    width:${size}px;
                    height:${size}px;
                    background:${color};
                    box-shadow:0 0 6px ${color};
                    animation-duration:${duration}s;
                    animation-delay:${delay}s;
                `;

                container.appendChild(el);
                setTimeout(() => el.remove(), (duration + delay) * 1000);
            }

            setInterval(spawnEmber, 600);
        })();
    </script>


    <!-- ===== SLIDER JS ===== -->
    <script>
        let current = 0;
        const slides = document.querySelectorAll('.slide');
        const dots = document.querySelectorAll('.dot');

        function goToSlide(n) {
            slides[current].classList.remove('active');
            dots[current].classList.remove('active');
            current = n;
            slides[current].classList.add('active');
            dots[current].classList.add('active');
        }

        function nextSlide() {
            goToSlide((current + 1) % slides.length);
        }

        setInterval(nextSlide, 4500);
    </script>



@endsection